### ISSUE TITLE
$PMANAGEMENT_SERVICE_ACCOUNT_NAME unassigned variable

### ISSUE THREAD

**Issue by ktedore** [seung-lab/CAVEdeployment#19]
https://github.com/seung-lab/CAVEdeployment/blob/ef10795f57b3b41ae23f3726253d8578845fec81/infrastructure/local/create_service_accounts.sh#L17

https://github.com/seung-lab/CAVEdeployment/blob/ef10795f57b3b41ae23f3726253d8578845fec81/infrastructure/local/create_service_accounts.sh#L18

https://github.com/seung-lab/CAVEdeployment/blob/ef10795f57b3b41ae23f3726253d8578845fec81/infrastructure/local/create_service_accounts.sh#L36

**Comment by fcollman** [comment]
this is now fixed
