### ISSUE TITLE
postgresql password in quotes? 

### ISSUE THREAD

**Issue by ktedore** [seung-lab/CAVEdeployment#2]
This line fails for me if the password is not in quotes.

https://github.com/seung-lab/CAVEdeployment/blob/9f3b106267f6146127bdf48864722684206a171d/infrastructure/global/launch_cluster.sh#L21

**Comment by ktedore** [comment]
Only an issue if using special characters.

**Comment by fcollman** [comment]
yeah agreed this should be changed..
